### ISSUE TITLE
add modules support

### ISSUE THREAD

**Issue by hallgren** [hallgren/eventsourcing#18]

**Comment by hallgren** [comment]
In branch `go_modules` but need more reading to know if this is correctly done.

**Comment by lunjon** [comment]
The branch `go_modules` looks fine to me. May I suggest to add Travis CI to make automated builds and deploys as well? The following travis file would work (I think):

```yaml
language: go

go:
- 1.13.x

env:
  # Not sure if needed for go 1.13
  - GO111MODULE=on 

jobs:
  include:
    - stage: build
      script:
        - go get ./...
        - go test ./...
      deploy:
        provider: releases
        # Requires that an environment variable named $GH_TOKEN is available,
        # set to a valid GitHub API key.
        api_key: $GH_TOKEN
        skip_cleanup: true
        on:
          branch: master
          tags: true
```

A new tag on branch master would cause an automated release, which is nice.
